# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


from olib.py.django.app.settingsbase import *  # pylint: disable=wildcard-import,unused-wildcard-import

###########################################################
# Application definition
###########################################################

INSTALLED_APPS += [
    'olib.py.django.xauth',
    'olib.py.django.celery_workers',
    'olib.py.django.conf',
    'olib.py.django.test',  # Models for test
]

ROOT_URLCONF = 'olib.py.django._app.urls'
WSGI_APPLICATION = 'olib.py.django._app.wsgi.application'
