extends: default

rules:
  comments:
    ignore: |
      # Ignore Jinja2 syntax
      {%.*%}
      {{.*}}
  brackets:
    max-spaces-inside: -1
  braces:
    max-spaces-inside: -1
  colons:
    max-spaces-after: -1
  indentation:
    indent-sequences: false