# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.0.3 on 2024-03-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinesetting',
            options={'default_permissions': ('view', 'change')},
        ),
    ]
